# Site settings
title: The Emotional Programmer
email: louis.phil@gmail.com
description: "My thoughts on software development, architecture and the education of software developers"
baseurl: "http://www.louissalin.com/"
url: "http://louissalin.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
